# ref: https://iss.ndl.go.jp/information/wp-content/uploads/2022/05/ndlsearch_api_20220520_jp.pdf
getsru:
	curl 'https://iss.ndl.go.jp/api/sru?operation=searchRetrieve&query=isbn%3d%229784480088161%22' > NationalDietLibrary/sru.xml
getos:
	curl https://iss.ndl.go.jp/api/opensearch?isbn=9784480088161 > NationalDietLibrary/opensearch.xml

# TODO: 表紙画像も欲しい
